### ISSUE TITLE
TypeError: Cannot convert undefined or null to object at Function.entries

### ISSUE THREAD

**Issue by fatihyildizhan** [meilisearch/mini-dashboard#209] opened 2021-11-30 12:13 UTC
**Describe the bug**
Mini-dashboard gives an error after indexing via C# API an object like this. But, properties are not null. Also, I am able to search with the API. Only the dashboard is not working.

```
public class Bodrum
{
  public string Yalikavak { get; set; }
  public string Istanbul { get; set; }
  public int Ankara { get; set; }
  public int Biga { get; set; }
  public IEnumerable<string> Izmir { get; set; }
  public IEnumerable<string> Fethiye { get; set; }
}
```

**To Reproduce**
1. Index this object 
2. Open Mini-dasboard
3. Set the API key
4. Mini-dasboard shows the error.

It also gives header is missing error.

**Screenshots**
![dashboard error](https://user-images.githubusercontent.com/602600/144045161-fa56f7bf-ae98-47fc-b864-187ac171992e.png)

**MeiliSearch version:** [e.g. v0.24.0]

**Comment by mdubus** [comment] 2021-11-30 13:56
Hello @fatihyildizhan  !

First of all, thank you for your bug report ! 
Could you please give me more context about the error ? 

Are you using the [Dotnet](https://github.com/meilisearch/meilisearch-dotnet) SDK to index your documents ? 
Could you provide an example of the documents you have indexed so that I can try to reproduce it ? 

Thanks a lot !

**Comment by fatihyildizhan** [comment] 2021-11-30 16:24
@mdubus 

I found the cause of the error. There is a property named `Length`. I think it's a default name for Meilisearch. Problem solved when I changed the name.

**Comment by mdubus** [comment] 2021-12-01 07:36
Hello @fatihyildizhan !

I see that you have closed and then reopened this issue. It is solved, or do you need any help on it ? 😀

**Comment by fatihyildizhan** [comment] 2021-12-01 11:38
@mdubus I changed my model's property name and fixed my problem. But, I think this is an issue and can happen to someone else too. So, maybe you should fix it. That's why I re-opened the issue.

**Comment by mdubus** [comment] 2022-02-16 09:32
Closing as I can't reproduce. If the problem is still there, please open a new issue issue with details about how to reproduce the bug 🙏

**Closed by mdubus** 2022-02-16 09:32 UTC
